### ISSUE TITLE
CSS selectors tempremental?

### ISSUE THREAD

**Issue by crushgh** [apify/actor-content-checker#8]
It might be just me - but I'm having mixed results using CSS selectors to correctly identify the area to be captured. 

For example, using `div#PDP_productPrice` on `https://www.boots.com/no7-men-anti-ageing-bundle`, throws the error

```
2020-11-08T18:05:46.717Z ERROR The function passed to Apify.main() threw an exception:
2020-11-08T18:05:46.719Z   Error: Cannot get screenshot (screenshot selector is probably wrong)
2020-11-08T18:05:46.721Z       at /home/myuser/main.js:64:15
2020-11-08T18:05:46.722Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

which in my mind is not expected behaviour. Am I right?

**Comment by RoneoOrg** [comment]
Hi @crushgh,

did you manage to sort this out?

I stumbled [on a similar issue](https://github.com/apify/actor-content-checker/issues/15), tried for hours.. I'm stuck!

Any hint would be welcome!

**Comment by metalwarrior665** [comment]
Sorry for late reply. We are adding logic to get screenshot of failed page which should show you what rendered. We are also adding retries for blocked pages.
